In [20]:
import os
import pandas as pd
import yasa
import datetime

In [51]:
sleep_data = pd.read_csv(os.path.join('..', 'data','pmi-mini_pilot','4de37ee3-7baf-4592-a431-a6d01fff6bd1',
                                      'WRSD-PMI-01_c3ea8756-8e12-45b7-a31c-1a03e398daf9',
                                      'garmin-connect-sleep-stage',
                                      '000000_garmin-connect-sleep-stage_WRSD-PMI-01_c3ea8756.csv'), skiprows=5)

sleep_summary = pd.read_csv(os.path.join('..', 'data','pmi-mini_pilot','4de37ee3-7baf-4592-a431-a6d01fff6bd1',
                                      'WRSD-PMI-01_c3ea8756-8e12-45b7-a31c-1a03e398daf9',
                                      'garmin-connect-sleep-summary',
                                      '000000_garmin-connect-sleep-summary_WRSD-PMI-01_c3ea8756.csv'), skiprows=5)

In [52]:
sleep_data['isoDate'] = pd.to_datetime(sleep_data['unixTimestampInMs'] + sleep_data['timezoneOffsetInMs'], unit='ms', utc=True)
sleep_data['isoDate'] = sleep_data['isoDate'].dt.tz_localize(None)

sleep_summary['calendarDate'] = pd.to_datetime(sleep_summary['calendarDate'], format='%Y-%m-%d')

In [53]:
calendar_date = datetime.datetime(2023, 3, 23)

In [54]:
sleep_stat_row = sleep_summary[sleep_summary.calendarDate == calendar_date]
sleep_start_time = pd.to_datetime((sleep_stat_row['unixTimestampInMs'] + sleep_stat_row['timezoneOffsetInMs']), unit='ms', utc=True).dt.tz_localize(None).iloc[0]
sleep_end_time = pd.to_datetime((sleep_stat_row['unixTimestampInMs'] + sleep_stat_row['timezoneOffsetInMs'] + sleep_stat_row['durationInMs']), unit='ms', utc=True).dt.tz_localize(None).iloc[0]

In [55]:
sleep_data[(sleep_data.isoDate >= sleep_start_time) & (sleep_data.isoDate <= sleep_end_time)]

,sleepSummaryId,timezoneOffsetInMs,unixTimestampInMs,isoDate,durationInMs,type
0,x3ef5923-641b7d30-5f64,3600000,1679523120000,2023-03-22 23:12:00,600000,light
1,x3ef5923-641b7d30-5f64,3600000,1679523720000,2023-03-22 23:22:00,1020000,deep
2,x3ef5923-641b7d30-5f64,3600000,1679524740000,2023-03-22 23:39:00,900000,light
3,x3ef5923-641b7d30-5f64,3600000,1679525640000,2023-03-22 23:54:00,2520000,deep
4,x3ef5923-641b7d30-5f64,3600000,1679528160000,2023-03-23 00:36:00,840000,light
5,x3ef5923-641b7d30-5f64,3600000,1679529000000,2023-03-23 00:50:00,60000,awake
6,x3ef5923-641b7d30-5f64,3600000,1679529060000,2023-03-23 00:51:00,600000,light
7,x3ef5923-641b7d30-5f64,3600000,1679529660000,2023-03-23 01:01:00,1140000,rem
8,x3ef5923-641b7d30-5f64,3600000,1679530800000,2023-03-23 01:20:00,360000,light
9,x3ef5923-641b7d30-5f64,3600000,1679531160000,2023-03-23 01:26:00,1080000,deep
10,x3ef5923-641b7d30-5f64,3600000,1679532240000,2023-03-23 01:44:00,60000,awake
11,x3ef5923-641b7d30-5f64,3600000,1679532300000,2023-03-23 01:45:00,420000,light
12,x3ef5923-641b7d30-5f64,3600000,1679532720000,2023-03-23 01:52:00,1080000,deep
13,x3ef5923-641b7d30-5f64,3600000,1679533800000,2023-03-23 02:10:00,840000,light
14,x3ef5923-641b7d30-5f64,3600000,1679534640000,2023-03-23 02:24:00,360000,rem
15,x3ef5923-641b7d30-5f64,3600000,1679535000000,2023-03-23 02:30:00,1860000,light
16,x3ef5923-641b7d30-5f64,3600000,1679536860000,2023-03-23 03:01:00,840000,deep
17,x3ef5923-641b7d30-5f64,3600000,1679537700000,2023-03-23 03:15:00,1500000,light
18,x3ef5923-641b7d30-5f64,3600000,1679539200000,2023-03-23 03:40:00,720000,rem
19,x3ef5923-641b7d30-5f64,3600000,1679539920000,2023-03-23 03:52:00,720000,light
20,x3ef5923-641b7d30-5f64,3600000,1679540640000,2023-03-23 04:04:00,420000,rem
21,x3ef5923-641b7d30-5f64,3600000,1679541060000,2023-03-23 04:11:00,960000,light
22,x3ef5923-641b7d30-5f64,3600000,1679542020000,2023-03-23 04:27:00,840000,rem
23,x3ef5923-641b7d30-5f64,3600000,1679542860000,2023-03-23 04:41:00,1200000,light
24,x3ef5923-641b7d30-5f64,3600000,1679544060000,2023-03-23 05:01:00,300000,deep
25,x3ef5923-641b7d30-5f64,3600000,1679544360000,2023-03-23 05:06:00,2040000,light
26,x3ef5923-641b7d30-5f64,3600000,1679546400000,2023-03-23 05:40:00,780000,rem
27,x3ef5923-641b7d30-5f64,3600000,1679547180000,2023-03-23 05:53:00,60000,awake
28,x3ef5923-641b7d30-5f64,3600000,1679547240000,2023-03-23 05:54:00,480000,light

In [77]:
intervals = int(divmod((sleep_end_time - sleep_start_time).total_seconds(), 60)[0])
one_minute_intervals = [sleep_start_time + i * datetime.timedelta(minutes=1) for i in range(intervals)]

hypnogram = pd.DataFrame(data={
    'isoDate': one_minute_intervals 
})

In [78]:
hypnogram = hypnogram.merge(sleep_data.loc[:, ['isoDate','type']], how='left', on='isoDate')
hypnogram.head()

              isoDate   type
0 2023-03-22 23:12:00  light
1 2023-03-22 23:13:00    NaN
2 2023-03-22 23:14:00    NaN
3 2023-03-22 23:15:00    NaN
4 2023-03-22 23:16:00    NaN

In [81]:
hypnogram['type'] = hypnogram.loc[:, 'type'].fillna(method='ffill')

In [85]:
hypnogram

                isoDate   type  type-yasa
0   2023-03-22 23:12:00  light          1
1   2023-03-22 23:13:00  light          1
2   2023-03-22 23:14:00  light          1
3   2023-03-22 23:15:00  light          1
4   2023-03-22 23:16:00  light          1
..                  ...    ...        ...
402 2023-03-23 05:54:00  light          1
403 2023-03-23 05:55:00  light          1
404 2023-03-23 05:56:00  light          1
405 2023-03-23 05:57:00  light          1
406 2023-03-23 05:58:00  light          1

[407 rows x 3 columns]

In [83]:
"""
The default hypnogram format in YASA is a 1D integer vector where:
-2 = Unscored
-1 = Artefact / Movement
0 = Wake -> awake
1 = N1 sleep -> light
2 = N2 sleep
3 = N3 sleep -> deep
4 = REM sleep -> rem
"""
def from_garmin_to_yasa(x):
    if x == 'rem':
        return 4
    elif x == 'awake':
        return 0
    elif x == 'deep':
        return 3
    else:
        return 1

In [84]:
hypnogram['type-yasa'] = hypnogram['type'].apply(from_garmin_to_yasa)
yasa.sleep_statistics(hypnogram['type-yasa'], 1/60)

{'TIB': 407.0,
 'SPT': 407.0,
 'WASO': 3.0,
 'TST': 404.0,
 'N1': 219.0,
 'N2': 0.0,
 'N3': 114.0,
 'REM': 71.0,
 'NREM': 333.0,
 'SOL': 0.0,
 'Lat_N1': 0.0,
 'Lat_N2': nan,
 'Lat_N3': 10.0,
 'Lat_REM': 109.0,
 '%N1': 54.20792079207921,
 '%N2': 0.0,
 '%N3': 28.217821782178216,
 '%REM': 17.574257425742573,
 '%NREM': 82.42574257425743,
 'SE': 99.26289926289927,
 'SME': 99.26289926289927}

In [86]:
hypnogram['type-yasa']

0      1
1      1
2      1
3      1
4      1
      ..
402    1
403    1
404    1
405    1
406    1
Name: type-yasa, Length: 407, dtype: int64